"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
format = """
$directory\
$git_status\
$status\
$character
"""

# move the rest of the prompt to the right
# right_format = """$all"""
right_format = """
$username\
$hostname\
$localip\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$docker_context\
$package\
$cmake\
$golang\
$helm\
$nodejs\
$python\
$ruby\
$rust\
$memory_usage\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$os\
$container\
$shell
"""

scan_timeout = 10 # timeout for file scans
command_timeout = 300 # timeout for commands called from starship

add_newline = false

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[time]
disabled = false
format = '🕙[\[$time\]]($style) '
time_format = '%T'

[git_status]
conflicted = '🏳'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
up_to_date = '[✓](green)'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](yellow)'
renamed = '👅'
deleted = '🗑'

[git_branch]
symbol = ' '
#ignore_branches = ['m']
truncation_length = 8

[status]
style = 'bg:red'
map_symbol = true
disabled = false

# [python]
# style = "green bold"
# format = '[${symbol}${pyenv_prefix}(${version} )]($style)[(\($virtualenv\) )](yellow)'

[username]
format = '[$user]($style) on '

[hostname]
ssh_symbol = '🌐'
format = '[$ssh_symbol$hostname]($style) '
trim_at = ''

[kubernetes]
disabled = false
symbol = '🐳☸ '
format = '[$symbol$context(| $namespace)]($style) '

[kubernetes.context_aliases]
